---
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    hostname: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  ultimate-ai-streaming:
    container_name: ultimate-ai-spark-streaming
    depends_on:
      - mongodb
    build: .
