.PHONY: lint
lint:
	poetry run pre-commit run --all-files

.PHONY: test
test:
	poetry run pytest tests/ --disable-pytest-warnings

.PHONY: start
start:
	docker-compose up --build -d

.PHONY: stop
stop:
	docker-compose down --remove-orphans
