.PHONY: lint
lint:
	poetry run pre-commit run --all-files

.PHONY: test
test:
	poetry run pytest --cov-config=.coveragerc --cov=stream_processor/ --cache-clear --color=yes tests/ --disable-pytest-warnings
